for /f "delims=" %%i in ('dir /ad /b') do (cubemapgen.exe ^
-importFaceXPos:%%i\PositiveX.png ^
-importFaceXNeg:%%i\NegativeX.png ^
-importFaceYPos:%%i\PositiveY.png ^
-importFaceYNeg:%%i\NegativeY.png ^
-importFaceZPos:%%i\PositiveZ.png ^
-importFaceZNeg:%%i\NegativeZ.png ^
-exportFilename:..\..\..\Textures\Box\%%i.dds ^
-filterTech:AngularGaussian ^
-exportSize:256 ^
-exportMipChain ^
-exportPixelFormat:A8R8G8B8 ^
-exportCubeDDS ^
-exit && rd /s /q %%i)